name: Build Discord Bot

on:
  push:
    branches:
      - master
    paths:
      - bot/**
  repository_dispatch:
    types: 
      - build-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build & Publish Container with tag
      if: github.event.client_payload.tag
      run: echo ${{ github.event.client_payload.tag }}
    
    - name: Build & Publish Container as latest
      if: github.event_name == 'push' || !github.event.client_payload.tag
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: ${{ secrets.DOCKER_USERNAME }}/minecraft-link-bot
        context: bot
        dockerfile: dockerfile
