name: Build Discord Bot

on:
  push:
    branches:
      - master
    paths:
      - bot/**
  repository_dispatch:
    types: 
      - build-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Get image tag
      id: tag
      run: |
        if [ -z "$TAG" ]
        then
            echo "::set-output name=tag::latest"
        else
            echo "::set-output name=tag::$TAG"
        fi
      env:
        TAG: ${{ github.event.client_payload.tag }}
        
    - run: echo '${{ steps.tag.outputs.tag }}'
    
    - name: Build & Publish Container
      if: ${{ false }}
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: ${{ secrets.DOCKER_USERNAME }}/minecraft-link-bot
        context: bot
        dockerfile: dockerfile
        image-tag: ${{ steps.tag.outputs.tag }} 
