name: Create mod release

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
  repository_dispatch:
    types: [ release-mod ] 

jobs:
      
  publish:
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: PssbleTrngle/VersionManagment@v1.0.3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          prefix: v
        id: version
        
      - name: Create Release
        if: ${{ false }}
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: Release ${{ steps.version.outputs.next }}  
        
      - name: Build Mod
        run: chmod +x ./gradlew && ./gradlew build
