name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
    paths-ignore: [ bot ]

jobs:

  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: PssbleTrngle/VersionManagment@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: version
          
      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'build.properties'
          property: 'mod_version'
          value: ${{ steps.version.outputs.next }} 
        
      - name: Build Mod
        if: contains(github.event.pull_request.labels.*.name, 'release')
        run: chmod +x ./gradlew && ./gradlew build
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
          
      - name: Update Changelog
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: CHANGELOG.md
          contents: |
            .
            
            ## [${{ steps.version.outputs.next }}] - ${{ steps.date.outputs.date }}
            ${{ github.event.pull_request.body }}
          write-mode: append
                 
      - name: Upload to CurseForge
        if: contains(github.event.pull_request.labels.*.name, 'release')
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 408390
          game_endpoint: minecraft
          file_path: build/libs/discord-link-${{ steps.version.outputs.next }}.jar
          changelog: ${{ github.event.pull_request.body }}
          changelog_type: markdown  
          display_name: Version ${{ steps.version.outputs.next }}
          game_versions: 7892,4458,7499
          release_type: release
        
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: Release ${{ steps.version.outputs.next }}
          body: ${{ github.event.pull_request.body }}

      - name: Upload Mod Jar
        if: contains(github.event.pull_request.labels.*.name, 'release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/discord-link-${{ steps.version.outputs.next }}.jar
          asset_name: discord-link.jar
          asset_content_type: application/java-archive

      - name: Upload Source Jar
        if: contains(github.event.pull_request.labels.*.name, 'release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/discord-link-${{ steps.version.outputs.next }}-sources.jar
          asset_name: discord-link-sources.jar
          asset_content_type: application/java-archive

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v4
        with:
          message: Update Changelog
          add: build.properties CHANGELOG.md
          ref: master
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}