name: Create mod release

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
  repository_dispatch:
    types: [ release-mod ] 

jobs:
      
  publish:
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: PossibleTriangle/VersionManagment@v1.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          prefix: v
        id: version
        
      - name: Output next version
        run: echo ${{ steps.version.outputs.next }}
      
